USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS INSURANCE_CLAIMS;

CREATE SCHEMA IF NOT EXISTS INSURANCE_CLAIMS.ANALYTICS;

CREATE STAGE IF NOT EXISTS INSURANCE_CLAIMS.ANALYTICS.CLAIMS_STAGE;

CREATE OR REPLACE FILE FORMAT INSURANCE_CLAIMS.ANALYTICS.CLAIMS_CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL');

CREATE OR REPLACE TABLE INSURANCE_CLAIMS.ANALYTICS.CLAIMS_RAW (
    claim_id VARCHAR,
    policy_id VARCHAR,
    customer_age INTEGER,
    state VARCHAR,
    policy_type VARCHAR,
    claim_type VARCHAR,
    claim_date DATE,
    reported_date DATE,
    claim_amount NUMBER(12,2),
    approved_amount NUMBER(12,2),
    claim_status VARCHAR,
    processing_days INTEGER,
    fraud_flag BOOLEAN
);