USE WAREHOUSE COMPUTE_WH;

COPY INTO INSURANCE_CLAIMS.ANALYTICS.CLAIMS_RAW
FROM @INSURANCE_CLAIMS.ANALYTICS.CLAIMS_STAGE
FILE_FORMAT = (
    FORMAT_NAME = INSURANCE_CLAIMS.ANALYTICS.CLAIMS_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT';